# Generated by Django 2.0.4 on 2018-05-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='add class name here', max_length=30, verbose_name='Class Name')),
                ('begindate', models.DateField(help_text='add begin date here', verbose_name='Begin Date')),
                ('enddate', models.DateField(help_text='add end date here', verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='add section name here', max_length=30, verbose_name='Section Name')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='add first name here', max_length=30, verbose_name='First Name')),
                ('lastname', models.CharField(help_text='add last name here', max_length=30, verbose_name='Last Name')),
                ('fathername', models.CharField(help_text='add last name here', max_length=30, verbose_name="Father's Name")),
                ('fatherscnic', models.BigIntegerField(help_text="Guardian's CNIC Number here", max_length=13, verbose_name="Guardian's CNIC Number")),
                ('studentscnic', models.BigIntegerField(help_text="Guardian's CNIC Number here", max_length=13, verbose_name="Guardian's CNIC Number")),
                ('fathersnumber', models.BigIntegerField(help_text="Guardian's CNIC Number here", max_length=11, verbose_name="Guardian's CNIC Number")),
                ('studentsnumber', models.BigIntegerField(help_text="Guardian's CNIC Number here", max_length=11, verbose_name="Guardian's CNIC Number")),
            ],
        ),
        migrations.CreateModel(
            name='UC_Chapter',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4)),
                ('password', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ManagementSystem.Students')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManagementSystem.Section'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSystem.Class'),
        ),
    ]
