# Generated by Django 2.0.4 on 2018-05-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0002_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManagementSystem.Batch'),
        ),
    ]
