# Generated by Django 2.0.4 on 2018-06-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0004_auto_20180602_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSystem.Class', verbose_name='Class ID'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ManagementSystem.Students', verbose_name='Student ID'),
        ),
    ]
