# Generated by Django 2.0.4 on 2018-06-12 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0005_auto_20180612_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSystem.Students', verbose_name='Student ID'),
        ),
    ]
